#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "ERROR: No arguments supplied"
    exit 1
fi

#sleep 30

while :
do
    sleep 10
        
    p=`ping -c 1 10.0.0.254`
    pr=`echo $?`
    
    if [ $pr -eq 0 ]; then
        echo "all good"
        
    else
        echo "can't reach antenna on $1, force restart"
        ifconfig $1 down
        sleep 1
        ifconfig $1 up
    fi
done

